import type { EmployeeInput } from '../types/employee'

export const emptyEmployeeInput: EmployeeInput = {
  name: '',
  nameAr: '',
  email: '',
  phone: '',
  dateOfBirth: '',
  hireDate: '',
  status: 'active',
  militaryStatus: 'not_applicable',
  maritalStatus: 'single',
  healthCertificateImage: '',
  idCardImage: '',
  licenseImage: '',
  birthCertificateImage: '',
  jobTitle: '',
  jobTitleAr: '',
  subDepartment: '',
  subDepartmentAr: '',
  managerId: 0,
  managerName: '',
  managerNameAr: '',
  annualLeaveBalance: 21,
  sickLeaveBalance: 10,
  salary: 0,
  deductions: 0,
  penalties: 0,
}
